export const ArticleTagSlugsToVals = (tagSlug: string) => {
    if (tagSlug === "ent") return "娛樂";
    else if (tagSlug === "env") return "環境";
    else if (tagSlug === "jus") return "司法";
    else if (tagSlug === "cnd") return "國家發展";
    else if (tagSlug === "eco") return "經濟";
    else if (tagSlug === "min") return "少數族群";
    else if (tagSlug === "mda") return "媒體";
    else if (tagSlug === "med") return "醫藥";
    else if (tagSlug === "eth") return "道德";
    else if (tagSlug === "pol") return "政治";
    else if (tagSlug === "edu") return "教育";
    else if (tagSlug === "fam") return "家庭";
    else if (tagSlug === "fem") return "女性";
    else if (tagSlug === "lib") return "自由";
    else if (tagSlug === "rel") return "宗教";
    else if (tagSlug === "tec") return "科技";
    else if (tagSlug === "plc") return "社會政策";
    else if (tagSlug === "scm") return "社會運動";
    else if (tagSlug === "spr") return "體育";
    else throw new Error("Invalid slug");
};

export const ArticleTagValsToSlugs = (tagVal: string) => {
    if (tagVal === "娛樂") return "ent";
    else if (tagVal === "環境") return "env";
    else if (tagVal === "司法") return "jus";
    else if (tagVal === "國家發展") return "cnd";
    else if (tagVal === "經濟") return "eco";
    else if (tagVal === "少數族群") return "min";
    else if (tagVal === "媒體") return "mda";
    else if (tagVal === "醫藥") return "med";
    else if (tagVal === "道德") return "eth";
    else if (tagVal === "政治") return "pol";
    else if (tagVal === "教育") return "edu";
    else if (tagVal === "家庭") return "fam";
    else if (tagVal === "女性") return "fem";
    else if (tagVal === "自由") return "lib";
    else if (tagVal === "宗教") return "rel";
    else if (tagVal === "科技") return "tec";
    else if (tagVal === "社會政策") return "plc";
    else if (tagVal === "社會運動") return "scm";
    else if (tagVal === "體育") return "spr";
    else throw new Error("Invalid value");
};
