import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto flex h-screen flex-col items-center justify-center ">
                <h1>Speakup Indev</h1>
            </main>
        </>
    );
};

export default Home;
