name: Daily data index
on:
    schedule:
        - cron: "* */24 * * *"
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Clear article views
              run: |
                  curl --request POST \
                  --url 'https://speakup.place/api/privileged/clear/views' \
                  --header 'Authorization: Bearer ${{ secrets.ADMIN_KEY }}'
            - name: Clear preview article views
              run: |
                  curl --request POST \
                  --url 'https://speakup-preview.vercel.app/api/privileged/clear/views' \
                  --header 'Authorization: Bearer ${{ secrets.ADMIN_KEY }}'
